[versions]
junit = "4.13.2"
guice = "7.0.0"
byte-buddy = "1.18.3"
jmock = "2.13.1"

[libraries]
junit = { module = "junit:junit", version.ref = "junit" }
guice = { module = "com.google.inject:guice", version.ref = "guice" }
byte-buddy = { module = "net.bytebuddy:byte-buddy", version.ref = "byte-buddy" }
jmock-junit4 = { module = "org.jmock:jmock-junit4", version.ref = "jmock" }
jmock-imposters = { module = "org.jmock:jmock-imposters", version.ref = "jmock" }

[bundles]
jmock = ["byte-buddy", "jmock-junit4", "jmock-imposters"]
